# https://www.digitalocean.com/community/tutorials/how-to-use-traefik-as-a-reverse-proxy-for-docker-containers-on-ubuntu-18-04

version: "3.7"

services:
  traefik:
    image: traefik:2.1
    restart: always
    ports:
      - '80:80'
      - '443:443'
    volumes:
    - ./traefik:/etc/traefik
    - /var/run/docker.sock:/var/run/docker.sock:ro

  client:
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "./:/itmo-app/client"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.client.rule=Host(`sb0101.ru`)"
      - "traefik.http.routers.client.tls=true"
      - "traefik.http.routers.client.tls.certresolver=lets-encrypt"
