version: "3"

services:
  nginx:
    image: nginx:latest
    depends_on:
      - server
      # - client
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./packages/proxy/deploy/nginx:/etc/nginx/conf.d
      - ./packages/proxy/deploy/certbot/conf:/etc/letsencrypt
      - ./packages/proxy/deploy/certbot/www:/var/www/certbot
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''

  certbot:
    image: certbot/certbot
    volumes:
      - ./packages/proxy/deploy/certbot/conf:/etc/letsencrypt
      - ./packages/proxy/deploy/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  server:
    build:
      context: ./packages/server
      dockerfile: Dockerfile
    ports:
      - 5000:5000

  # client:
  #   build:
  #     context: ./packages/client
  #     dockerfile: Dockerfile
