version: "3"

services:
  nginx:
    image: valian/docker-nginx-auto-ssl
    restart: on-failure
    ports:
      - 80:80
      - 443:443
    volumes:
      - ssl_data:/etc/resty-auto-ssl
      - client-build:/usr/share/nginx/html
      - ./packages/client:/etc/nginx/conf.d
    environment:
      # ALLOWED_DOMAINS: sb0101.online api.sb0101.online"
      SITES: "api.sb0101.online=server:5000"

  server:
    build:
      context: ./packages/server
      dockerfile: Dockerfile
    ports:
      - 5000:5000

  client:
    build:
      context: ./packages/client
      dockerfile: Dockerfile
    volumes:
      - client-build:/itmo-app-client/build

volumes:
  ssl_data:
  client-build:
