version: "3.7"

services:
  database:
    image: mongo:latest
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=itmo-app-database
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=s3cr3tPa55w0rd
    ports:
      - "27017:27017"
    volumes:
      - ./packages/database/mongo-volume:/itmo-app/database
      - ./packages/database/init.js:/docker-entrypoint-initdb.d/init.js:ro

  database-ui:
    image: mongo-express:latest
    ports:
      - "8081:8081"
    # links:
    #   - database
    depends_on:
      - database
    environment:
      - ME_CONFIG_MONGODB_SERVER=database
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=s3cr3tPa55w0rd
      - ME_CONFIG_BASICAUTH_USERNAME=moder
      - ME_CONFIG_BASICAUTH_PASSWORD=letmein

  server:
    build:
      context: ./packages/server
      dockerfile: Dockerfile
    volumes:
      - "./packages/server:/itmo-app/server"
      - "/itmo-app/server/node_modules"
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
    depends_on: 
      - database

  client:
    stdin_open: true
    build:
      context: ./packages/client
      dockerfile: Dockerfile
    volumes:
      - "./packages/client:/itmo-app/client"
      - "/itmo-app/client/node_modules"
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
