version: '3'
services: 
    mongodb: 
        image: mongo:latest
        restart: always
        container_name: 'itmo-app-database'
        environment: 
            - MONGO_INITDB_DATABASE=itmo-app-database
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=s3cr3tPa55w0rd
        ports: 
            - '27017:27017'
        volumes: 
            - ./mongo-volume:/data/db
            - ./init.js:/docker-entrypoint-initdb.d/init.js:ro