name: Deploy master branch
on: [push]
jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_HOST_USERNAME }}
          password: ${{ secrets.DEPLOY_HOST_PASSWORD }}
          script_stop: true
          script: |
            cd apps/gtfo-cdo
            uname -a
            git pull
            yarn install
            yarn build
            pm2 restart gtfo-cdo
