name: Deploy master branch
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_HOST_USERNAME }}
          password: ${{ secrets.DEPLOY_HOST_PASSWORD }}
          script_stop: true
          script: |
            cd apps/gtfo-cdo
            uname -a
            git pull
            /root/.yarn/bin/yarn install
            /root/.yarn/bin/yarn build
            /root/.nvm/versions/node/v12.16.0/bin/pm2 restart gtfo-cdo
# Какая-то шляпа происходит, программы можно запустить только по абсолютному пути
# Нужно будет обязательно переделать по нормальному